"""add inventory_deducted

Revision ID: 5711054d0ca8
Revises: 1bbe38268c55
Create Date: 2026-07-08 10:17:15.634542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5711054d0ca8'
down_revision: Union[str, Sequence[str], None] = '1bbe38268c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('inventory_deducted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'inventory_deducted')
    # ### end Alembic commands ###
