"""scope_idempotency_key_per_tenant

Revision ID: 891a7f14119f
Revises: 5711054d0ca8
Create Date: 2026-07-19 22:57:38.170220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891a7f14119f'
down_revision: Union[str, Sequence[str], None] = '5711054d0ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_idempotency_key_key'), 'orders', type_='unique')
    op.create_unique_constraint('uq_order_restaurant_idempotency_key', 'orders', ['restaurant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_restaurant_idempotency_key', 'orders', type_='unique')
    op.create_unique_constraint(op.f('orders_idempotency_key_key'), 'orders', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
