"""Add restaurant_id to units

Revision ID: e98c54354e81
Revises: 891a7f14119f
Create Date: 2026-07-21 05:55:27.029885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e98c54354e81'
down_revision: Union[str, Sequence[str], None] = '891a7f14119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('units', sa.Column('restaurant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('units_name_key'), 'units', type_='unique')
    op.create_index(op.f('ix_units_restaurant_id'), 'units', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'units', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_index(op.f('ix_units_restaurant_id'), table_name='units')
    op.create_unique_constraint(op.f('units_name_key'), 'units', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('units', 'restaurant_id')

    # ### end Alembic commands ###
